name: systemjvj
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  table_calendar: ^3.2.0
  syncfusion_flutter_calendar: ^31.1.20
  shared_preferences: ^2.5.3
  open_file: ^3.5.10
  intl: ^0.20.2
  flutter_typeahead: ^5.2.0
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.2.0
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.1
  signature: ^6.3.0
  geolocator: ^14.0.1
  image: ^4.5.4
  native_exif: ^0.6.2
  geocoding: ^4.0.0
  workmanager: ^0.9.0+3
  package_info_plus: ^9.0.0
  speech_to_text: ^7.3.0
  share_plus: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
