name: systemjvj
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  table_calendar: ^3.0.9
  syncfusion_flutter_calendar: ^30.2.4
  shared_preferences: ^2.0.18
  excel: ^4.0.6
  open_file: ^3.3.1
  intl: ^0.20.2
  flutter_typeahead: ^5.2.0
  path_provider: ^2.0.11
  connectivity_plus: ^6.1.4
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  workmanager: ^0.9.0+2
  uuid: ^4.5.1
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true